module.exports = {
  "A01": "Metro Center",
  "A02": "Farragut North",
  "A03": "Dupont Circle",
  "A04": "Woodley Park-Zoo/Adams Morgan",
  "A05": "Cleveland Park",
  "A06": "Van Ness-UDC",
  "A07": "Tenleytown-AU",
  "A08": "Friendship Heights",
  "A09": "Bethesda",
  "A10": "Medical Center",
  "A11": "Grosvenor-Strathmore",
  "A12": "White Flint",
  "A13": "Twinbrook",
  "A14": "Rockville",
  "A15": "Shady Grove",
  "A99": "Shady Grove Yard",
  "B01": "Gallery Pl-Chinatown",
  "B02": "Judiciary Square",
  "B03": "Union Station",
  "B35": "New York Ave-Florida Ave-Gallaudet U",
  "B04": "Rhode Island Ave-Brentwood",
  "B05": "Brookland-CUA",
  "B06": "Fort Totten",
  "B07": "Takoma",
  "B08": "Silver Spring",
  "B09": "Forest Glen",
  "B10": "Wheaton",
  "B11": "Glenmont",
  "B98": "Glenmont Yard",
  "B99": "Brentwood Yard",
  "C01": "Metro Center",
  "C02": "McPherson Sq",
  "C03": "Farragut West",
  "C04": "Foggy Bottom-GWU",
  "C05": "Rosslyn",
  "C06": "Arlington Cemetery",
  "C07": "Pentagon",
  "C08": "Pentagon City",
  "C09": "Crystal City",
  "C10": "Ronald Reagan Washington National Airport",
  "C11": "Potomac Yard",
  "C12": "Braddock Road",
  "C13": "King Street",
  "C14": "Eisenhower Ave",
  "C15": "Huntington",
  "C97": "C & J Junction",
  "C98": "Alexandria Yard Leads",
  "C99": "Alexandria Yard",
  "D01": "Federal Triangle",
  "D02": "Smithsonian",
  "D03": "L'Enfant Plaza",
  "D04": "Federal Center SW",
  "D05": "Capitol South",
  "D06": "Eastern Market",
  "D07": "Potomac Ave",
  "D08": "Stadium-Armory",
  "D09": "Minnesota Ave",
  "D10": "Deanwood",
  "D11": "Cheverly",
  "D12": "Landover",
  "D13": "New Carrolton",
  "D99": "New Carrolton Yard",
  "E01": "Mt Vernon Sq/7th St-Convention Center",
  "E02": "Shaw-Howard U",
  "E03": "U St/African-Amer Civil War Memorial/Cardozo",
  "E04": "Columbia Heights",
  "E05": "Georgia Ave-Petworth",
  "E06": "Fort Totten",
  "E07": "West Hyattsville",
  "E08": "Prince George's Plaza",
  "E09": "College Park-U of MD",
  "E10": "Greenbelt",
  "E99": "Greenbelt Yard",
  "F01": "Gallery Pl-Chinatown",
  "F02": "Archives-Navy Mem'l-Penn Quarter",
  "F03": "L'Enfant Plaza",
  "F04": "Waterfront-SEU",
  "F05": "Navy Yard",
  "F06": "Anacostia",
  "F07": "Congress Heights",
  "F08": "Southern Ave",
  "F09": "Naylor Road",
  "F10": "Suitland",
  "F11": "Branch Avenue",
  "F99": "Branch Avenue Yard",
  "G01": "Benning Road",
  "G02": "Capitol Heights",
  "G03": "Addison Road-Seat Pleasant",
  "G04": "Morgan Boulevard",
  "G05": "Largo Town Center",
  "J01": "Quaker Lane",
  "J02": "Van Dorn Street",
  "J03": "Franconia-Springfield",
  "K01": "Court House",
  "K02": "Clarendon",
  "K03": "Virginia Sq-GMU",
  "K04": "Ballston-MU",
  "K05": "East Falls Church",
  "K06": "West Falls Church-VT/UVA",
  "K07": "Dunn Loring-Merrifield",
  "K08": "Vienna/Fairfax-GMU",
  "K99": "Falls Church Yard",
  "N01": "McLean",
  "N02": "Tysons Corner",
  "N03": "Greensboro",
  "N04": "Spring Hill",
  "N06": "Wiehle – Reston East"
}